import asyncio
import io
import pathlib
from pathlib import Path

import aiofiles
import discord
from Crypto.Random import random as rand
from discord.ext import commands

from modules.TZBot import TZBot
from shared import Helpers


class ImageGen(commands.Cog):
    colorSet: set[tuple[int, int, int]]

    def __init__(this, client: TZBot) -> None:
        this.client = client
        asyncio.create_task(this.loadColorSet())

    async def loadColorSet(this) -> None:
        if not pathlib.Path("colorlist.bin").is_file():
            this.colorSet = set()
            return

        async with aiofiles.open("colorlist.bin", "rb") as f:
            data = await f.read()
            this.colorSet = {(data[i], data[i + 1], data[i + 2]) for i in range(0, len(data), 3)}

    @discord.slash_command(name="generate", description="Generate an image using math!")
    @commands.cooldown(1, 10, commands.BucketType.user)
    async def generate(
        this,
        ctx: discord.ApplicationContext,
        r: discord.Option(str, "Math expression for red") = "0",
        g: discord.Option(str, "Math expression for green") = "0",
        b: discord.Option(str, "Math expression for blue") = "0",
    ) -> None:
        if not await Helpers.generateImage(r, g, b):
            await ctx.response.send_message("An error occured. Please try again.", ephemeral=True)
            ctx.command.reset_cooldown(ctx)
            return

        async with aiofiles.open("output.png", "rb") as f:
            file = discord.File(io.BytesIO(await f.read()), filename="pattern.png")

        await ctx.response.send_message("Here's your picture!", file=file)
        Path.unlink(Path("output.png"), missing_ok=True)

    @discord.slash_command(name="color", description="Generate a random unique (or not unique) color! Uses crypto random")
    @commands.cooldown(1, 3, commands.BucketType.user)
    async def color(this, ctx: discord.ApplicationContext) -> None:
        color: tuple[int, int, int] = (rand.randint(0, 255), rand.randint(0, 255), rand.randint(0, 255))
        fileOutput = color[0].to_bytes(1, byteorder="little") + color[1].to_bytes(1, byteorder="little") + color[2].to_bytes(1, byteorder="little")

        if not await Helpers.generateImage(str(color[0]), str(color[1]), str(color[2])):
            await ctx.response.send_message("An error occured. Please try again.", ephemeral=True)
            ctx.command.reset_cooldown(ctx)
            return

        async with aiofiles.open("output.png", "rb") as f:
            file = discord.File(io.BytesIO(await f.read()), filename="color.png")

        if color not in this.colorSet:
            await ctx.response.send_message(
                " ".join([f"**#{format(color[0], '02x')}{format(color[1], '02x')}{format(color[2], '02x')}** is", "your random unique color!"]),
                file=file,
            )

            this.colorSet.add(color)
            async with aiofiles.open("colorlist.bin", "ab") as writer:
                await writer.write(fileOutput)

        else:
            await ctx.response.send_message(
                " ".join(
                    [
                        f"**#{format(color[0], '02x')}{format(color[1], '02x')}{format(color[2], '02x')}**",
                        f"was already generated by someone. Duplicate after **{len(this.colorSet)}** total tries. That's",
                        f"~**{str((len(this.colorSet) * 100) / (256**3)).replace('.', ',')} %** chance! How unlucky! (or lucky?)",
                    ]
                ),
                file=discord.File(f),
            )

        Path.unlink(Path("output.png"), missing_ok=True)

    @generate.error
    @color.error
    async def generation_error(this, ctx: discord.ApplicationContext, error: Exception) -> None:
        if isinstance(error, commands.CommandOnCooldown):
            embed = this.client.fail.copy()
            embed.description = "This command is on cooldown!"

            await ctx.response.send_message(embed=embed, ephemeral=True)


def setup(client: TZBot) -> None:
    client.add_cog(ImageGen(client))
